"""
Integration Tests for Full Analysis Pipelines

Tests that complete analysis scripts run end-to-end successfully.
These tests ensure the entire workflow works, not just individual components.
"""

import pytest
import pandas as pd
import subprocess
import sys
from pathlib import Path
import time

# Repository root
REPO_ROOT = Path(__file__).parent.parent


class TestFreeAgentAnalysisPipeline:
    """Test full free agent analysis pipeline."""

    def test_contract_data_loads(self):
        """Test that ContractData loads free agents successfully."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.data import ContractData

        contracts = ContractData()
        fa_list = contracts.get_all_free_agents()

        # Should have free agents
        assert len(fa_list) > 0, "Should have loaded free agents"

        # Should have required columns
        assert 'player_name' in fa_list.columns
        assert 'position' in fa_list.columns
        assert 'age_2025' in fa_list.columns
        assert '2025_war' in fa_list.columns

        # All players should have valid data
        assert fa_list['player_name'].notna().all()
        assert fa_list['2025_war'].notna().all()

    def test_aging_curve_analyzer_executes(self):
        """Test that AgingCurveAnalyzer runs without errors."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.analysis import AgingCurveAnalyzer

        analyzer = AgingCurveAnalyzer()

        # Test projection
        projection = analyzer.calculate_contract_war(
            current_war=5.0,
            current_age=28,
            position='OF',
            contract_years=6
        )

        # Should return valid projection
        assert 'total_war' in projection
        assert 'yearly_projections' in projection
        assert len(projection['yearly_projections']) == 6

    def test_free_agent_analyzer_executes(self):
        """Test that FreeAgentAnalyzer runs without errors."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.analysis import FreeAgentAnalyzer

        analyzer = FreeAgentAnalyzer(dollars_per_war=8.0)

        # Create sample data
        sample_data = pd.DataFrame({
            'player_name': ['Test Player'],
            'woba': [0.350],
            'xwoba': [0.365],
            'barrel_batted_rate': [0.12],
            'hard_hit_rate': [0.45]
        })

        fa_list = pd.DataFrame({
            'player_name': ['Test Player'],
            'position': ['OF'],
            'age_2025': [28],
            '2025_war': [4.5]
        })

        # Should analyze without errors
        result = analyzer.analyze_free_agent_class(
            sample_data,
            fa_list,
            player_name_col='player_name'
        )

        assert isinstance(result, pd.DataFrame)
        assert len(result) > 0

    @pytest.mark.integration
    @pytest.mark.slow
    def test_full_fa_analysis_script_exists(self):
        """Test that main FA analysis script exists and is executable."""
        script_path = REPO_ROOT / 'run_real_fa_analysis.py'
        assert script_path.exists(), "FA analysis script should exist"

        # Script should be readable
        with open(script_path) as f:
            content = f.read()
            assert 'ContractData' in content or 'FreeAgent' in content, \
                "Script should import FA analysis modules"

    @pytest.mark.integration
    def test_data_directory_structure(self):
        """Test that data directory has expected structure."""
        data_dir = REPO_ROOT / 'data'

        # Data directory should exist
        assert data_dir.exists(), "Data directory should exist"

        # Check for key data files (may or may not exist depending on execution)
        expected_files = [
            '2025_fa_complete_real_data.csv',
            '2025_fangraphs_batting.csv',
            '2025_fangraphs_pitching.csv'
        ]

        # At least cache directory should exist
        cache_dir = data_dir / 'cache'
        if not cache_dir.exists():
            # If no data files, that's ok - they're generated by scripts
            pytest.skip("Data files not generated yet - run analysis scripts first")


class TestDataFetchingIntegration:
    """Test data fetching integration."""

    def test_fangraphs_fetcher_imports(self):
        """Test that FanGraphsFetcher can be imported."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.data import FanGraphsFetcher

        fetcher = FanGraphsFetcher()
        assert fetcher is not None

    def test_savant_leaderboards_imports(self):
        """Test that SavantLeaderboards can be imported."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        try:
            from src.data import SavantLeaderboards
            fetcher = SavantLeaderboards()
            assert fetcher is not None
        except ImportError:
            pytest.skip("SavantLeaderboards not available")


class TestAnalysisModulesIntegration:
    """Test that all analysis modules integrate correctly."""

    def test_all_analysis_modules_import(self):
        """Test that all analysis modules can be imported."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))

        # Core modules
        from src.analysis import AgingCurveAnalyzer
        from src.analysis import FreeAgentAnalyzer
        from src.analysis import BreakoutDetector

        # All should instantiate
        assert AgingCurveAnalyzer() is not None
        assert FreeAgentAnalyzer() is not None
        assert BreakoutDetector() is not None

    def test_injury_risk_analyzer_imports(self):
        """Test that InjuryRiskAnalyzer imports."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.analysis.injury_risk_analyzer import InjuryRiskAnalyzer

        analyzer = InjuryRiskAnalyzer()
        assert analyzer is not None
        assert hasattr(analyzer, 'calculate_pitcher_injury_risk')
        assert hasattr(analyzer, 'calculate_batter_injury_risk')

    def test_contract_optimizer_imports(self):
        """Test that ContractStructureOptimizer imports."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.analysis.contract_structure_optimizer import ContractStructureOptimizer

        optimizer = ContractStructureOptimizer()
        assert optimizer is not None
        assert hasattr(optimizer, 'calculate_npv')

    def test_metrics_module_functions(self):
        """Test that metrics module has expected functions."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.analysis import metrics

        # Should have key metric functions
        assert hasattr(metrics, 'calculate_woba')
        assert hasattr(metrics, 'calculate_barrel_rate')


class TestEndToEndWorkflow:
    """Test complete end-to-end workflows."""

    @pytest.mark.integration
    def test_complete_fa_evaluation_workflow(self):
        """Test complete FA evaluation workflow from data to analysis."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))

        from src.data import ContractData
        from src.analysis import AgingCurveAnalyzer, FreeAgentAnalyzer

        # Step 1: Load FA data
        contracts = ContractData()
        fa_list = contracts.get_all_free_agents()
        assert len(fa_list) > 0, "Should have FAs"

        # Step 2: Analyze aging curves for top FA
        top_fa = fa_list.nlargest(1, '2025_war').iloc[0]

        analyzer = AgingCurveAnalyzer()
        projection = analyzer.calculate_contract_war(
            current_war=top_fa['2025_war'],
            current_age=top_fa['age_2025'],
            position=top_fa['position'],
            contract_years=5
        )

        # Should get projection
        assert projection['total_war'] > 0
        assert len(projection['yearly_projections']) == 5

        # Step 3: Calculate contract value
        fa_analyzer = FreeAgentAnalyzer(dollars_per_war=8.0)
        value = fa_analyzer._calculate_contract_value(projection['total_war'])

        # Should get realistic value
        assert value > 0
        assert value < 500, "Contract value should be < $500M"

    @pytest.mark.integration
    def test_injury_risk_integration(self):
        """Test injury risk analysis integration."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))

        from src.analysis.injury_risk_analyzer import InjuryRiskAnalyzer

        analyzer = InjuryRiskAnalyzer()

        # Create sample pitcher data
        sample_pitcher = pd.DataFrame({
            'Name': ['Test Pitcher'],
            'Age': [32],
            'fastball_velo_trend_mph': [-2.5],
            'cumulative_ip_3yr': [680],
            'k_rate_decline_pct': [-5.0]
        })

        result = analyzer.calculate_pitcher_injury_risk(sample_pitcher)

        # Should have injury risk score
        assert 'injury_risk_score' in result.columns
        assert result.iloc[0]['injury_risk_score'] > 0

    @pytest.mark.integration
    def test_contract_structure_integration(self):
        """Test contract structure optimization integration."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))

        from src.analysis.contract_structure_optimizer import (
            ContractStructureOptimizer,
            ContractStructure
        )

        optimizer = ContractStructureOptimizer(discount_rate=0.05)

        # Create sample contract
        contract = ContractStructure(
            total_value=200.0,
            years=8,
            aav=25.0,
            deferred_pct=0.50,
            deferral_years=5
        )

        # Calculate NPV
        npv = optimizer.calculate_npv(contract)

        # Should get NPV analysis
        assert 'npv' in npv
        assert 'deferral_discount' in npv
        assert npv['npv'] < contract.total_value


class TestOutputGeneration:
    """Test that outputs are generated correctly."""

    @pytest.mark.integration
    def test_csv_generation_capability(self):
        """Test that we can generate CSV outputs."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.data import ContractData

        contracts = ContractData()
        fa_list = contracts.get_all_free_agents()

        # Should be able to save to CSV
        output_path = REPO_ROOT / 'data' / 'test_output.csv'
        fa_list.to_csv(output_path, index=False)

        # File should exist
        assert output_path.exists()

        # Should be readable
        df_check = pd.read_csv(output_path)
        assert len(df_check) == len(fa_list)

        # Clean up
        output_path.unlink()

    @pytest.mark.integration
    def test_markdown_report_generation(self):
        """Test that we can generate markdown reports."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.data import ContractData

        contracts = ContractData()
        fa_list = contracts.get_all_free_agents()

        # Generate simple markdown report
        report = "# Free Agent Analysis\n\n"
        report += f"Total Free Agents: {len(fa_list)}\n\n"
        report += "## Top 5 by WAR\n\n"

        top_5 = fa_list.nlargest(5, '2025_war')
        for _, fa in top_5.iterrows():
            report += f"- {fa['player_name']} ({fa['position']}, {fa['age_2025']}): {fa['2025_war']:.1f} WAR\n"

        # Should have content
        assert len(report) > 100
        assert 'Free Agent Analysis' in report


class TestErrorHandling:
    """Test that pipelines handle errors gracefully."""

    def test_missing_data_handling(self):
        """Test that missing data is handled gracefully."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.analysis import AgingCurveAnalyzer

        analyzer = AgingCurveAnalyzer()

        # Test with edge case data
        try:
            projection = analyzer.calculate_contract_war(
                current_war=0.0,  # Edge case: 0 WAR
                current_age=25,
                position='OF',
                contract_years=1
            )
            # Should not crash
            assert 'total_war' in projection
        except Exception as e:
            pytest.fail(f"Should handle 0 WAR gracefully: {e}")

    def test_invalid_position_handling(self):
        """Test handling of invalid position codes."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.analysis import AgingCurveAnalyzer

        analyzer = AgingCurveAnalyzer()

        # Should handle unknown position
        # Either use default or raise informative error
        try:
            projection = analyzer.calculate_contract_war(
                current_war=3.0,
                current_age=28,
                position='INVALID',  # Invalid position
                contract_years=3
            )
            # If it doesn't crash, should have fallback behavior
            assert 'total_war' in projection
        except (ValueError, KeyError) as e:
            # Acceptable to raise informative error
            assert 'position' in str(e).lower() or 'invalid' in str(e).lower()


class TestPerformance:
    """Test performance of key operations."""

    def test_aging_curve_calculation_speed(self):
        """Test that aging curve calculations are fast."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.analysis import AgingCurveAnalyzer

        analyzer = AgingCurveAnalyzer()

        # Time 100 projections
        start_time = time.time()

        for i in range(100):
            analyzer.calculate_contract_war(
                current_war=5.0,
                current_age=28,
                position='OF',
                contract_years=5
            )

        elapsed = time.time() - start_time

        # Should complete in < 1 second
        assert elapsed < 1.0, f"100 projections took {elapsed:.2f}s (should be <1s)"

    def test_fa_list_loading_speed(self):
        """Test that FA list loads quickly."""
        sys.path.insert(0, str(REPO_ROOT / 'src'))
        from src.data import ContractData

        # Time FA list loading
        start_time = time.time()

        contracts = ContractData()
        fa_list = contracts.get_all_free_agents()

        elapsed = time.time() - start_time

        # Should load in < 5 seconds
        assert elapsed < 5.0, f"FA list loading took {elapsed:.2f}s (should be <5s)"


if __name__ == '__main__':
    pytest.main([__file__, '-v', '-m', 'not slow'])
